export const WORK_KINDS: Record<string, { kind: string; verbs: string[] }> = {
  "amateur-archaeology": { kind: "an excavated fragment, field record, catalogued artifact, or reconstruction", verbs: ["excavated", "catalogued", "reconstructed"] },
  baking: { kind: "a baked object, recipe experiment, or edible failure", verbs: ["baked", "prepared", "removed from the oven"] },
  birdwatching: { kind: "a recorded sighting, field sketch, or behavioral observation", verbs: ["observed", "sketched", "recorded"] },
  "building-small-machines": { kind: "a named device, mechanism, instrument, or failed prototype", verbs: ["built", "assembled", "tested"] },
  chess: { kind: "a chess position, problem, match record, opening, or tactical study", verbs: ["composed", "played", "recorded"] },
  coding: { kind: "a small program, protocol, function, interface, or corrupted tool", verbs: ["wrote", "compiled", "released"] },
  "collecting-strange-objects": { kind: "a newly acquired and catalogued strange object", verbs: ["collected", "catalogued", "found"] },
  gardening: { kind: "a cultivated specimen, planting arrangement, or growing experiment", verbs: ["grew", "cultivated", "planted"] },
  journaling: { kind: "a dated journal fragment, observation, list, or private record", verbs: ["wrote", "recorded", "entered"] },
  mapmaking: { kind: "a map, route, boundary study, or chart of a possible place", verbs: ["mapped", "charted", "surveyed"] },
  meditation: { kind: "a named meditation, breathing record, realization, or documented interruption", verbs: ["completed", "recorded", "practiced"] },
  "metal-detecting": { kind: "a detected and unearthed object with a specific physical form", verbs: ["unearthed", "detected", "found"] },
  "mushroom-hunting": { kind: "a mushroom specimen, field sketch, spore record, or encounter", verbs: ["found", "catalogued", "sketched"] },
  painting: { kind: "an individual painting with a concrete subject and composition", verbs: ["painted", "completed", "made"] },
  photography: { kind: "a particular photograph with a subject, framing, and captured moment", verbs: ["photographed", "captured", "developed"] },
  "puzzle-solving": { kind: "a puzzle, partial solution, solved mechanism, or deduction record", verbs: ["solved", "constructed", "decoded"] },
  "radio-listening": { kind: "an intercepted transmission, frequency log, or recorded broadcast", verbs: ["intercepted", "recorded", "received"] },
  stargazing: { kind: "an observation, star chart, invented constellation, or night-sky record", verbs: ["observed", "charted", "named"] },
  storytelling: { kind: "a compact story, folktale, scene, or recovered oral fragment", verbs: ["told", "wrote", "recovered"] },
  woodworking: { kind: "a carved or constructed wooden object with a practical or strange purpose", verbs: ["carved", "built", "assembled"] },
};
